# Generated by Django 6.0.4 on 2026-05-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionsession',
            name='highlighted_transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
